### ISSUE TITLE
Failed on loading initial data

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bmihelac/ra-data-django-rest-framework#10]
Running `./migrate.py loaddata initial` returns the following error:

```
./manage.py loaddata initial
Traceback (most recent call last):
  File "/home/rafaellehmkuhl/Development/dash-test/ra-data-django-rest-framework/example/backend/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rafaellehmkuhl/Development/dash-test/ra-data-django-rest-framework/example/backend/.venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: django_content_type.app_label, django_content_type.model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)

  [...]

  File "/home/rafaellehmkuhl/Development/dash-test/ra-data-django-rest-framework/example/backend/.venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: Problem installing fixture '/home/rafaellehmkuhl/Development/dash-test/ra-data-django-rest-framework/example/backend/exampleapp/fixtures/initial.json': Could not load contenttypes.ContentType(pk=7): UNIQUE constraint failed: django_content_type.app_label, django_content_type.model
```

**Comment by bmihelac** [comment]
This should be fixed, thanks for reporting
